In [1]:
import numpy as np

In [2]:
array_1_to_20 = np.arange(1, 21)
print(f"The array is: {array_1_to_20}\n")

The array is: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]



In [3]:
array_sum = np.sum(array_1_to_20)
array_mean = np.mean(array_1_to_20)
array_median = np.median(array_1_to_20)
array_std = np.std(array_1_to_20)

print(f"Sum of elements: {array_sum}")
print(f"Mean of elements: {array_mean}")
print(f"Median of elements: {array_median}")
print(f"Standard deviation of elements: {array_std}\n")

Sum of elements: 210
Mean of elements: 10.5
Median of elements: 10.5
Standard deviation of elements: 5.766281297335398



In [4]:
mask_greater_than_10 = array_1_to_20 > 10

In [5]:
indices_greater_than_10 = np.where(mask_greater_than_10)

In [6]:
indices_list = indices_greater_than_10[0]

print(f"Indices of elements greater than 10: {indices_list}")
print(f"Elements at these indices: {array_1_to_20[indices_list]}")

Indices of elements greater than 10: [10 11 12 13 14 15 16 17 18 19]
Elements at these indices: [11 12 13 14 15 16 17 18 19 20]


In [8]:
array_2d = array_1_to_20.reshape(4, 5)
transpose_array = array_2d.T
print("Original Array:\n", array_2d)
print("Transpose of the Array:\n", transpose_array)

Original Array:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
Transpose of the Array:
 [[ 1  6 11 16]
 [ 2  7 12 17]
 [ 3  8 13 18]
 [ 4  9 14 19]
 [ 5 10 15 20]]


In [9]:
row_sums = array_2d.sum(axis=1)
col_sums = array_2d.sum(axis=0)
print("Row-wise Sums:", row_sums)
print("Column-wise Sums:", col_sums)

Row-wise Sums: [15 40 65 90]
Column-wise Sums: [34 38 42 46 50]


In [10]:
array1 = np.random.randint(1, 21, size=(3, 3))
array2 = np.random.randint(1, 21, size=(3, 3))
addition_result = array1 + array2
subtraction_result = array1 - array2
multiplication_result = array1 * array2
dot_product_result = np.dot(array1, array2)

print(f"Array 1:\n{array1}")
print(f"Array 2:\n{array2}")
print(f"Element-wise Addition:\n{addition_result}")
print(f"Element-wise Subtraction:\n{subtraction_result}")
print(f"Element-wise Multiplication:\n{multiplication_result}")
print(f"Dot Product:\n{dot_product_result}")

Array 1:
[[14  6 16]
 [18  8  2]
 [14 19  1]]
Array 2:
[[ 2 19  5]
 [ 5  5  7]
 [19 11  9]]
Element-wise Addition:
[[16 25 21]
 [23 13  9]
 [33 30 10]]
Element-wise Subtraction:
[[ 12 -13  11]
 [ 13   3  -5]
 [ -5   8  -8]]
Element-wise Multiplication:
[[ 28 114  80]
 [ 90  40  14]
 [266 209   9]]
Dot Product:
[[362 472 256]
 [114 404 164]
 [142 372 212]]


In [11]:
arr_1d = np.arange(1, 13)
print("Original 1D array:")
print(arr_1d)
arr_2d = arr_1d.reshape(3, 4)
print("\nReshaped 3x4 2D array:")
print(arr_2d)
sliced_arr = arr_2d[:2, 2:]
print("\nSliced array (first two rows, last two columns):")
print(sliced_arr)

Original 1D array:
[ 1  2  3  4  5  6  7  8  9 10 11 12]

Reshaped 3x4 2D array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Sliced array (first two rows, last two columns):
[[3 4]
 [7 8]]
