<a href="https://colab.research.google.com/github/Vihaanyo2/Vihaan/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np
arr = np.random.randint(10,100)
arr

56

In [6]:
import numpy as np
arr = np.random.randint(6,98)
arr

38

In [8]:
import numpy as np
arr = np.random.randint(6,98, size=(3,3))
arr

array([[50, 13, 80],
       [86, 90, 39],
       [17, 18, 60]])

In [9]:
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [10]:
print(type(arr))

<class 'numpy.ndarray'>


In [11]:
lst = ["string", 1,2,3,4.6]
arr = np.array(lst)
arr

array(['string', '1', '2', '3', '4.6'], dtype='<U32')

In [12]:
arr = np.array([1,2,3,4])
arr


array([1, 2, 3, 4])

In [14]:
arr.dtype

dtype('int64')

In [13]:
print(type(arr))

<class 'numpy.ndarray'>


In [15]:
new_arr = arr.astype(np.float64)
new_arr

array([1., 2., 3., 4.])

In [16]:
new_arr.dtype

dtype('float64')

In [17]:
new_arr2 = arr.astype(np.int64)
new_arr2

array([1, 2, 3, 4])

In [19]:
arr = np.array([[1,2,3], [4,5,6], [7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
arr.ndim

2

In [22]:
arr.shape

(3, 3)

In [23]:
arr.size

9

In [24]:
arr.itemsize

8

In [25]:
arr = np.array([1,2,3,4,5,6])
reshaped = arr.reshape(2,3)
print(reshaped)

[[1 2 3]
 [4 5 6]]


In [27]:
reshape2 = reshaped.reshape(3,2)
reshape2

array([[1, 2],
       [3, 4],
       [5, 6]])

In [28]:
ravel = reshape2.ravel()
ravel

array([1, 2, 3, 4, 5, 6])

In [29]:
ravel[0] = 100
print(ravel)
print(reshape2)

[100   2   3   4   5   6]
[[100   2]
 [  3   4]
 [  5   6]]


In [30]:
reshape2

array([[100,   2],
       [  3,   4],
       [  5,   6]])

In [32]:
flattened_array = reshape2.flatten()
flattened_array

array([100,   2,   3,   4,   5,   6])

In [33]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print(a+b)

[5 7 9]


In [34]:
print(a-b)

[-3 -3 -3]


In [35]:
print(b-a)

[3 3 3]


In [36]:
print(a/b)

[0.25 0.4  0.5 ]


In [39]:
print(b//a)

[4 2 2]


In [37]:
print(a*b)

[ 4 10 18]


In [41]:
print(b%a)

[0 1 0]


In [43]:
print(a**2)

[1 4 9]


In [4]:
import numpy as np
arr = np.array([1,4,9,16])
print(np.sqrt(arr))

[1. 2. 3. 4.]


In [6]:
print(np.exp([1,2]))

[2.71828183 7.3890561 ]


In [7]:
print(np.exp([2,3]))

[ 7.3890561  20.08553692]


In [8]:
angles = np.array([0,np.pi,np.pi/2])
print(np.sin(angles))

[0.0000000e+00 1.2246468e-16 1.0000000e+00]


In [10]:
a = [1,2,3,4,5]
a[-1:-4:-1]

[5, 4, 3]

In [11]:
a[2]

3

In [13]:
a[:  :2]

[1, 3, 5]

In [14]:
arr = np.array([10,20,30,40,50])
print(arr[::2])

[10 30 50]


In [17]:
print(arr[-1])

50


In [23]:
matrix = np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9]])
print(matrix[0:2])

[[1 2 3]
 [4 5 6]]


In [26]:
print(matrix[1:2 , 1:2])

[[5]]


In [30]:
arr = np.array([[1,2,3], [4,5,6]])
for x in np.nditer(arr):
    print(x, end = " ")

1 2 3 4 5 6 

In [31]:
arr = np.array([[1,2], [3,4]])
arr


array([[1, 2],
       [3, 4]])

In [32]:
print(arr.transpose())

[[1 3]
 [2 4]]


In [35]:
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6], [7,8]])
arr = np.concatenate((arr1, arr2))
print(arr)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [36]:
print(np.hstack((arr1, arr2)))

[[1 2 5 6]
 [3 4 7 8]]


In [11]:
import numpy as np
arr = np.array([1,2,3])
print(np.repeat(arr, repeats=3))
print(np.tile(arr, reps=2))

[1 1 1 2 2 2 3 3 3]
[1 2 3 1 2 3]


In [9]:
import numpy as np
arr = np.array([1,2,3])
print(np.tile(arr,2))

[1 2 3 1 2 3]


In [12]:
import pandas as pd
import numpy as np
ser = pd.Series(['a', np.nan, 1,np.nan, 2])
ser.notnull().sum()

np.int64(3)

In [14]:
arr = np.array([1,2,3,4,5])
print(np.sum(arr))

15


In [18]:
matrix = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(np.vstack((matrix)))


[[1 2 3]
 [4 5 6]
 [7 8 9]]
